export const region = {
  US: [
    { name: 'Alabama', code: 'AL' },
    { name: 'Alaska', code: 'AK' },
    { name: 'American Samoa', code: 'AS' },
    { name: 'Arizona', code: 'AZ' },
    { name: 'Arkansas', code: 'AR' },
    { name: 'California', code: 'CA' },
    { name: 'Colorado', code: 'CO' },
    { name: 'Connecticut', code: 'CT' },
    { name: 'Delaware', code: 'DE' },
    { name: 'District Of Columbia', code: 'DC' },
    { name: 'Federated States Of Micronesia', code: 'FM' },
    { name: 'Florida', code: 'FL' },
    { name: 'Georgia', code: 'GA' },
    { name: 'Guam', code: 'GU' },
    { name: 'Hawaii', code: 'HI' },
    { name: 'Idaho', code: 'ID' },
    { name: 'Illinois', code: 'IL' },
    { name: 'Indiana', code: 'IN' },
    { name: 'Iowa', code: 'IA' },
    { name: 'Kansas', code: 'KS' },
    { name: 'Kentucky', code: 'KY' },
    { name: 'Louisiana', code: 'LA' },
    { name: 'Maine', code: 'ME' },
    { name: 'Marshall Islands', code: 'MH' },
    { name: 'Maryland', code: 'MD' },
    { name: 'Massachusetts', code: 'MA' },
    { name: 'Michigan', code: 'MI' },
    { name: 'Minnesota', code: 'MN' },
    { name: 'Mississippi', code: 'MS' },
    { name: 'Missouri', code: 'MO' },
    { name: 'Montana', code: 'MT' },
    { name: 'Nebraska', code: 'NE' },
    { name: 'Nevada', code: 'NV' },
    { name: 'New Hampshire', code: 'NH' },
    { name: 'New Jersey', code: 'NJ' },
    { name: 'New Mexico', code: 'NM' },
    { name: 'New York', code: 'NY' },
    { name: 'North Carolina', code: 'NC' },
    { name: 'North Dakota', code: 'ND' },
    { name: 'Northern Mariana Islands', code: 'MP' },
    { name: 'Ohio', code: 'OH' },
    { name: 'Oklahoma', code: 'OK' },
    { name: 'Oregon', code: 'OR' },
    { name: 'Palau', code: 'PW' },
    { name: 'Pennsylvania', code: 'PA' },
    { name: 'Puerto Rico', code: 'PR' },
    { name: 'Rhode Island', code: 'RI' },
    { name: 'South Carolina', code: 'SC' },
    { name: 'South Dakota', code: 'SD' },
    { name: 'Tennessee', code: 'TN' },
    { name: 'Texas', code: 'TX' },
    { name: 'Utah', code: 'UT' },
    { name: 'Vermont', code: 'VT' },
    { name: 'Virgin Islands', code: 'VI' },
    { name: 'Virginia', code: 'VA' },
    { name: 'Washington', code: 'WA' },
    { name: 'West Virginia', code: 'WV' },
    { name: 'Wisconsin', code: 'WI' },
    { name: 'Wyoming', code: 'WY' },
  ],
  IT: [
    { name: 'Abruzzo', code: '65' },
    { name: 'Agrigento', code: 'AG' },
    { name: 'Alessandria', code: 'AL' },
    { name: 'Ancona', code: 'AN' },
    { name: 'Arezzo', code: 'AR' },
    { name: 'Ascoli Piceno', code: 'AP' },
    { name: 'Asti', code: 'AT' },
    { name: 'Avellino', code: 'AV' },
    { name: 'Bari', code: 'BA' },
    { name: 'Barletta-Andria-Trani', code: 'BT' },
    { name: 'Basilicata', code: '77' },
    { name: 'Belluno', code: 'BL' },
    { name: 'Benevento', code: 'BN' },
    { name: 'Bergamo', code: 'BG' },
    { name: 'Biella', code: 'BI' },
    { name: 'Bologna', code: 'BO' },
    { name: 'Bolzano', code: 'BZ' },
    { name: 'Bozen', code: 'BZ' },
    { name: 'Brescia', code: 'BS' },
    { name: 'Brindisi', code: 'BR' },
    { name: 'Cagliari', code: 'CA' },
    { name: 'Calabria', code: '78' },
    { name: 'Caltanissetta', code: 'CL' },
    { name: 'Campania', code: '72' },
    { name: 'Campobasso', code: 'CB' },
    { name: 'Caserta', code: 'CE' },
    { name: 'Catania', code: 'CT' },
    { name: 'Catanzaro', code: 'CZ' },
    { name: 'Chieti', code: 'CH' },
    { name: 'Como', code: 'CO' },
    { name: 'Cosenza', code: 'CS' },
    { name: 'Cremona', code: 'CR' },
    { name: 'Crotone', code: 'KR' },
    { name: 'Cuneo', code: 'CN' },
    { name: 'Emilia-Romagna', code: '45' },
    { name: 'Enna', code: 'EN' },
    { name: 'Fermo', code: 'FM' },
    { name: 'Ferrara', code: 'FE' },
    { name: 'Firenze', code: 'FI' },
    { name: 'Foggia', code: 'FG' },
    { name: 'Forlì-Cesena', code: 'FC*' },
    { name: 'Friuli Venezia Giulia', code: '36' },
    { name: 'Frosinone', code: 'FR' },
    { name: 'Genova', code: 'GE' },
    { name: 'Gorizia', code: 'GO' },
    { name: 'Grosseto', code: 'GR' },
    { name: 'Imperia', code: 'IM' },
    { name: 'Isernia', code: 'IS' },
    { name: "L'Aquila", code: 'AQ' },
    { name: 'La Spezia', code: 'SP' },
    { name: 'Latina', code: 'LT' },
    { name: 'Lazio', code: '62' },
    { name: 'Lecce', code: 'LE' },
    { name: 'Lecco', code: 'LC' },
    { name: 'Liguria', code: '42' },
    { name: 'Livorno', code: 'LI' },
    { name: 'Lodi', code: 'LO' },
    { name: 'Lombardia', code: '25' },
    { name: 'Lucca', code: 'LU' },
    { name: 'Macerata', code: 'MC' },
    { name: 'Mantova', code: 'MN' },
    { name: 'Marche', code: '57' },
    { name: 'Massa-Carrara', code: 'MS' },
    { name: 'Messina', code: 'ME' },
    { name: 'Milano', code: 'MI' },
    { name: 'Modena', code: 'MO' },
    { name: 'Molise', code: '67' },
    { name: 'Monza e Brianza', code: 'MB' },
    { name: 'Napoli', code: 'NA' },
    { name: 'Novara', code: 'NO' },
    { name: 'Nuoro', code: 'NU' },
    { name: 'Oristano', code: 'OR' },
    { name: 'Padova', code: 'PD' },
    { name: 'Palermo', code: 'PA' },
    { name: 'Parma', code: 'PR' },
    { name: 'Pavia', code: 'PV' },
    { name: 'Perugia', code: 'PG' },
    { name: 'Pesaro e Urbino', code: 'PU' },
    { name: 'Pescara', code: 'PE' },
    { name: 'Piacenza', code: 'PC' },
    { name: 'Piemonte', code: '21' },
    { name: 'Pisa', code: 'PI' },
    { name: 'Pistoia', code: 'PT' },
    { name: 'Pordenone', code: 'PN' },
    { name: 'Potenza', code: 'PZ' },
    { name: 'Prato', code: 'PO' },
    { name: 'Puglia', code: '75' },
    { name: 'Ragusa', code: 'RG' },
    { name: 'Ravenna', code: 'RA' },
    { name: 'Reggio Calabria', code: 'RC' },
    { name: 'Reggio Emilia', code: 'RE' },
    { name: 'Rieti', code: 'RI' },
    { name: 'Rimini', code: 'RN' },
    { name: 'Roma', code: 'RM' },
    { name: 'Rovigo', code: 'RO' },
    { name: 'Salerno', code: 'SA' },
    { name: 'Sardegna', code: '88' },
    { name: 'Sassari', code: 'SS' },
    { name: 'Savona', code: 'SV' },
    { name: 'Sicilia', code: '82' },
    { name: 'Siena', code: 'SI' },
    { name: 'Siracusa', code: 'SR' },
    { name: 'Sondrio', code: 'SO' },
    { name: 'Sud Sardegna', code: 'SU' },
    { name: 'Taranto', code: 'TA' },
    { name: 'Teramo', code: 'TE' },
    { name: 'Terni', code: 'TR' },
    { name: 'Torino', code: 'TO' },
    { name: 'Toscana', code: '52' },
    { name: 'Trapani', code: 'TP' },
    { name: 'Trentino-Alto Adige', code: '32' },
    { name: 'Trentino-Südtirol', code: '32' },
    { name: 'Trento', code: 'TN' },
    { name: 'Treviso', code: 'TV' },
    { name: 'Trieste', code: 'TS' },
    { name: 'Udine', code: 'UD' },
    { name: 'Umbria', code: '55' },
    { name: "Val d'Aoste", code: '23' },
    { name: "Valle d'Aosta", code: '23' },
    { name: 'Varese', code: 'VA' },
    { name: 'Veneto', code: '34' },
    { name: 'Venezia', code: 'VE' },
    { name: 'Verbano-Cusio-Ossola', code: 'VB' },
    { name: 'Vercelli', code: 'VC' },
    { name: 'Verona', code: 'VR' },
    { name: 'Vibo Valentia', code: 'VV' },
    { name: 'Vicenza', code: 'VI' },
    { name: 'Viterbo', code: 'VT' },
  ],
};
